# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='custmer_id',
            field=models.IntegerField(unique=True),
        ),
    ]
